---
site_name: Proxy 4
site_url: https://mingxwa.github.io/proxy
site_description: Next Generation Polymorphism in C++
site_author: Microsoft Windows Team

repo_url: https://github.com/microsoft/proxy/
edit_uri: ""

theme:
  name: material
  custom_dir: mkdocs-overrides
  font:
    text: Roboto
  palette:
    primary: black
  logo: resources/ms_icon.png
  favicon: resources/ms_icon.png
  features:
    - navigation.instant
    - navigation.indexes

plugins:
  - awesome-pages
  - git-revision-date-localized
  - search

markdown_extensions:
  - admonition
  - attr_list
  - mdx_truly_sane_lists
  - meta
  - pymdownx.highlight
  - pymdownx.pathconverter
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
