on:
  workflow_call:

jobs:
  bvt-appleclang:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4

    - name: check compiler versions
      run: |
        clang --version
        xcodebuild -version

    - name: build and run test with AppleClang
      run: |
        cmake -B build -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release
        cmake --build build -j
        ctest --test-dir build -j
