name: Proxy-CI

on:
  push:
    branches: [ main, release/** ]
  pull_request:
    branches: [ main, release/** ]
  workflow_dispatch:

jobs:
  run-bvt-nvhpc:
    uses: ./.github/workflows/bvt-nvhpc.yml
    name: Run BVT with NVHPC
