name: Proxy-CI

on:
  push:
    branches: [ main, release/** ]
  pull_request:
    branches: [ main, release/** ]
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  run-bvt-appleclang:
    uses: ./.github/workflows/bvt-appleclang.yml
    name: Run BVT with AppleClang
