---
name: Build mkdocs
on:
  push:
    branches:
      - user/mingxwa/doc
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  build-mkdocs:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
      contents: write
      deployments: write
      issues: write
      pages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref_name }}
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel==0.45.1 mkdocs==1.6.1 mkdocs-material==9.6.14 pymdown-extensions==10.15 markdown==3.8 mdx_truly_sane_lists==1.3 mkdocs-git-revision-date-localized-plugin==1.4.5 mkdocs-awesome-pages-plugin==2.10.1

      - name: Build site
        run: mkdocs build --strict

      - name: Deploy
        if: ${{ inputs.branch == null }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
